@startuml
== Создание записи ==

Client -> UGC_Service: Post запрос (key-value)
activate UGC_Service
UGC_Service -> Kafka: Сохранение данных в кластер
Etl --> Kafka: Инициализация Consumer для Redis
Kafka -> Etl: Получение данных
Etl -> Redis: Запись данных (key-value)
activate Etl
activate Kafka
activate Redis

== Получение данных ==
Client -> UGC_Service: Get запрос (key)
UGC_Service -> Redis: Запрос записи по ключу (key)
Redis -> UGC_Service: Значение по ключу
deactivate UGC_Service

== Перенос данных в ClickHouse ==

Etl --> Kafka: Инициализация Consumer для ClickHouse
activate ClickHouse
Kafka -> Etl: Передача данных
Etl -> ClickHouse: Запись данных в хранилище
Analyst -> ClickHouse: Построение запросов для аналитики
@enduml